### PR TITLE
Compiling fixes

### PR DESCRIPTION
**Pull request by coti**
Hello,
I tried to compile Microperf on my machine but I had to add some minor stuff to make it work. So here are my minor modifications, if I can contribute. I guess they might be useful for other people.
Camille

### CODE REVIEW

**Comment by jphalimi** [comment]
Thanks for the contribution. I merged your changes.

**Comment by coti** [comment]
thanks! :)

**Comment by jcbeyler** [comment]
Let us know if there are some features or comments about the tool; it has code rotted most likely but could be brought back to a former glory ;-)

**Comment by coti** [comment]
Well honestly I am currently digging into the code to see if I am using it incorrectly or if there is something I can patch.

I have followed the tutorial: I have generated assembly files with MicroCreator, I have run the example example0.c with MicroLauncher... and then, tadam, I have tried to run MicroLauncher with one of the assembly files I generated earlier with MicroCreator. I picked example00147.s randomly and I copied it in the examples folder. It seems to have a entryPoint function so I tried with:
`./microlaunch --kernelname example/example00147.s --kernelfunction entryPoint`

And then....

`[...]
#4993: ===================================
#4993: LAUNCHING BENCHMARK (KERNEL MODE)
#4993: ===================================
#4993: Launching Configuration :
#4993: 	- Meta-repetitions : 40
#4993: 	- Repetitions : 20
- Benchmark computation process : 100% (2500000/2500000)
*** Error in `./microlaunch': free(): invalid pointer: 0x00007f518f20a010 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bcb)[0x7f51940fdbcb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76f96)[0x7f5194103f96]
/lib/x86_64-linux-gnu/libc.so.6(+0x777de)[0x7f51941047de]
./microlaunch(Description_destroy+0x42)[0x55806f545bc2]
./microlaunch(main+0x3ed)[0x55806f53a02d]
[...]`

So I have been digging into the code and I found out that the line it crashes on is line 302 in Description.c:
`free (desc->dummyArrayNonAligned), desc->dummyArrayNonAligned = NULL;`
I am trying to see what happens with this pointer throughout the execution because the address itself does not change between the moment when it is malloc'ed and this tentative destruction. Moreover, I have no problem with the C code example....

**Comment by jcbeyler** [comment]
So weird, I just tried:
./microcreator examples/description_addpd.xml

then:
./microlaunch --kernelname ../microcreator/output/example00000.s --kernelfunction entryPoint

This works for me, what exact commands do you use, where did your example assembly code come from exactly?

**Comment by coti** [comment]
This one works perfectly for me too and so does example00002.s, but example00001.s does not...

The command I am using is:

`./microlaunch --kernelname ../microcreator/output/example00001.s --kernelfunction entryPoint`

The .s files were generate by:

`./microcreator examples/description_MOVAPD_st_L_LL_LLL.xml `

**Comment by jcbeyler** [comment]
Ok that fails for me too which is a good thing :) I created an issue for it and I'll look at what is going on:
https://github.com/LittleWhite-tb/microperf/issues/2

**Comment by jcbeyler** [comment]
So the reason it fails is because MOVAPD is using doubles, so you have to use the option --data-size=double. Then it works:

./microlaunch --kernelname ../microcreator/output/example00001.s --kernelfunction entryPoint --data-size=double

(Reason of failure is that basically by not saying data-size double, you allocate half of what is needed. The code is then writing over memory and ends up writing over parts of the description most likely).

One feature request would be to figure this out automatically but not sure how feasible that is :)

**Pull request merged**
